# Generated by Django 2.2.2 on 2019-10-05 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20191005_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='last_update',
            new_name='last_updated',
        ),
    ]
